---
title: "Homework 4"
author: "Yuki Joyama"
date: "2024-02-29"
output: 
  pdf_document: default
  github_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, message = F, warning = F)

library(tidyverse)
library(MASS)
library(nnet)
```

```{r}
# data prep
df_house = data.frame(
  contact = c(rep(c("low", "high"), times = c(3, 3))),
  type = c(rep(c("tower", "apartment", "house"), length.out = 3)), 
  sat.low = c(65, 130, 67, 34, 141, 130),
  sat.medium = c(54, 76, 48, 47, 116, 105),
  sat.high = c(100, 111, 62, 100, 191, 104)
)
```

## 1
```{r}
# calculate row-wise percentages
df_house$sat.low_per <- (df_house$sat.low / rowSums(df_house[, c("sat.low", "sat.medium", "sat.high")])) * 100
df_house$sat.medium_per <- (df_house$sat.medium / rowSums(df_house[, c("sat.low", "sat.medium", "sat.high")])) * 100
df_house$sat.high_per <- (df_house$sat.high / rowSums(df_house[, c("sat.low", "sat.medium", "sat.high")])) * 100

# table of percentages
df_house[-(3:5)]

# plot
df_house |> 
  dplyr::select(contact, type, sat.low_per, sat.medium_per, sat.high_per) |> 
  pivot_longer(cols = starts_with("sat."), 
               names_to = "sat", 
               values_to = "proportion") |> 
  mutate(sat = str_remove(sat, "sat\\.") |>  str_remove("_per")) |> 
# plot
  ggplot(aes(x = type, y = proportion, group = sat, color = sat)) +
  geom_line() +
  facet_grid(~contact) +
  theme_bw()
```

## 2
```{r results=F}
# fit a nominal logistic regression model
house.mult <- multinom(cbind(sat.low, sat.medium, sat.high) ~ factor(contact) + factor(type), data = df_house)
```

```{r}
summary(house.mult)
```



```{r}
# goodness of fit
pihat = predict(house.mult,type = 'probs') 
pihat
m = rowSums(df_house[, 3:5])

# pearson residuals 
res.pearson = (df_house[, 3:5] - pihat*m) / sqrt(pihat*m) 
res.pearson

# Generalized Pearson Chisq Stat
G.stat = sum(res.pearson^2) 
G.stat
pval = 1 - pchisq(G.stat, df = (6 - 4)*(3 - 1))
pval # fit is good, do not reject the model

# deviance
D.stat = sum(2*df_house[, 3:5]*log(df_house[, 3:5] / (m*pihat)))
D.stat
```

## 3
```{r}
# fit a ordinal logistic regression model

```


## 4
```{r}
# Pearson residuals 
```









