Homework 3
================
Yuki Joyama
2024-02-27

## 1

``` r
# data prep
df_ec = data.frame(
  age = c(25, 25, 35, 35, 45, 45, 55, 55, 65, 65, 75, 75),
  alcohol = c(rep(c("less", "more"), length.out = 12)),
  case = c(0, 1, 5, 4, 21, 25, 24, 42, 36, 19, 8, 5),
  control = c(106, 9, 164, 26, 138, 29, 139, 27, 88, 18, 31, 0)
) 

resp = cbind(df_ec$case, df_ec$control) 
```

We coded daily alcohol consumption 0-79g as “less”, and 80+g as “more”.

### a

``` r
# fit a prospective logit model
logit.prosp = glm(resp ~ df_ec$alcohol + df_ec$age, family = binomial(link = 'logit'))

summary(logit.prosp) 
```

    ## 
    ## Call:
    ## glm(formula = resp ~ df_ec$alcohol + df_ec$age, family = binomial(link = "logit"))
    ## 
    ## Coefficients:
    ##                    Estimate Std. Error z value Pr(>|z|)    
    ## (Intercept)       -5.142771   0.432049 -11.903   <2e-16 ***
    ## df_ec$alcoholmore  1.887764   0.190502   9.909   <2e-16 ***
    ## df_ec$age          0.061805   0.007485   8.258   <2e-16 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## (Dispersion parameter for binomial family taken to be 1)
    ## 
    ##     Null deviance: 214.750  on 11  degrees of freedom
    ## Residual deviance:  29.988  on  9  degrees of freedom
    ## AIC: 76.03
    ## 
    ## Number of Fisher Scoring iterations: 4

``` r
exp(coef(logit.prosp)) # odds ratio estimates
```

    ##       (Intercept) df_ec$alcoholmore         df_ec$age 
    ##       0.005841482       6.604582479       1.063755249

In this model, we treat disease status (case vs control) as response and
exposures (daily alcohol consumption and age) as predictors.

$logit(\pi_i)=\beta_0+\beta_1x_1+\beta_2x_2$  
$x_1:$ the indicator of heavier daily alcohol consumption (80+g)  
$x_2:$ the indicator of age (as a continuous variable)

- The odds ratio of having esophageal cancer is 6.605 in heavier daily
  alcohol consumer (80+g) compared to lighter consumer (0-79g) holding
  other covariates constant  
- As age increases by one year, the odds ratio of having esophageal
  cancer increases by 1.064 holding other covariates constant

### b
